#!/usr/bin/env sh

for f in $(find . -type f -name makefile.depend); do
    # backup good copy
    mv $f $f.bak

    # create empty file
    touch $f
    git add $f

    # restore backup
    rm $f
    mv $f.bak $f
done
