
#USE_LOCALES=true
#LOCALES=	de en es fr it

AS_STATIC=	true
SO_VERSION=	0.1.0

LIB=	cat
SRCS=	cat.c
OBJS=	cat.o
#MAN=	cat.1
MAN=	

LDADD=	

include $(PROJECT_ROOT)/maketools/posix.lib.mk
# vim: noet
# end of file 
