
#USE_LOCALES=true
#LOCALES=	de en es fr it

AS_STATIC=	true
SO_VERSION=	0.1.0

LIB=	printf
SRCS=	printf.c
OBJS=	printf.o
#MAN=	printf.1
MAN=	

LDADD=	

include $(PROJECT_ROOT)/maketools/posix.lib.mk
# vim: noet
# end of file 
