#!/usr/bin/env bash

timeout_span=90

for t in $*; do
    total_test_count=0 # necessary
    passed_test_count=0
    passed_test_percent=0
    failed_test_list=() # necessary
    failed_test_count=0

    echo "Testing '$(basename $t)'"
    while read -r line; do
        echo "    $line"
        [[ $line == 'not ok'* ]] && failed_test_list+=("`echo $line |awk -F\  '{ print $3 }'`")
        [[ $line == '1..'* ]] && total_test_count=$(echo "$line" |sed 's/1\.\.//')
    done <<< `timeout $timeout_span $t`
    failed_test_count="${#failed_test_list[@]}"
    passed_test_count=$((total_test_count - failed_test_count))
    [ $total_test_count != 0 ] && passed_test_percent=$(((passed_test_count * 100) / total_test_count))
    [ $failed_test_count -gt 0 ] && echo "FAILED tests `echo ${failed_test_list[@]} |sed 's/ /, /g'`"
    echo "Failed $failed_test_count/$total_test_count tests, $passed_test_percent% okay"
done

# end of file
