#!/usr/bin/env bash


suite_total=0
suite_fail_count=0
suite_failed=()

for t in $*; do
    test_failed=()
    test_total=0

    echo "Testing '$(basename $t)'"
    while read -r line; do
        echo "    $line"
        [[ $line == *'ok'* ]] && test_total=$((test_total+1))
        [[ $line == *'not ok'* ]] && test_failed+=("`echo $line |awk -F\  '{ print $3 }'`")
    done <<< `$t`
    fail_count="${#test_failed[@]}"
    pass_count=$((test_total - fail_count))
    pass_percent=$(((pass_count * 100) / test_total))
    if [ $fail_count -gt 0 ]; then
        echo "FAILED tests `echo ${test_failed[@]} |sed 's/ /, /g'`"
        suite_failed+=("$(basename $t): ${test_failed[@]}")
    fi
    echo "Failed $fail_count/$test_total tests, $pass_percent% okay"

    suite_total=$((suite_total + test_total));
    suite_fail_count=$((suite_fail_count + fail_count));
done

test_fail_count="${#suite_failed[@]}"
pass_count=$((suite_total - suite_fail_count))
pass_percent=$(((pass_count * 100) / suite_total))
echo "FAILED test suites ${suite_failed[@]}"
echo "Failed $test_fail_count/$suite_total suites, $pass_percent% okay"


# end of file
