
PROG=	basename

SRCS=	main.c
OBJS=	main.o
MAN=	
DEPS=	../core/libbasename.a

LDFLAGS=	-L../core -lbasename
CFLAGS= 	-I../core

include $(PROJECT_ROOT)/maketools/posix.prog.mk
# vim: noet
# end of file 
