
CATEGORIES=	LC_MESSAGES
LOCALES=	de en es fr it

AS_STATIC=	true
SO_VERSION=	0.1.0

LIB=	ls
SRCS=	ls.c
OBJS=	ls.o
MAN=	ls.1

LDADD=	-lm

include $(PROJECT_ROOT)/maketools/posix.lib.mk
# vim: noet
# end of file 
