
#USE_LOCALES=true
#LOCALES=	de en es fr it

AS_STATIC=	true
SO_VERSION=	0.1.0

LIB=	chgrp
SRCS=	chgrp.c
OBJS=	chgrp.o
#MAN=	chgrp.1
MAN=	

LDADD=	-lm

include $(PROJECT_ROOT)/maketools/posix.lib.mk
# vim: noet
# end of file 
